// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LpCarno.Templates
{
    using System.Collections.Generic;
    using LxTools;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class RacialStatistics : RacialStatisticsBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"{|class=""sortable wikitable"" style=""text-align:center;""

!colspan=2 align=left style=""border-left:  1px solid #777; border-top: 1px solid #777; border-right: 1px solid #777;"" |
!colspan=4 align=left style=""border-right: 1px solid #777; border-top: 1px solid #777;""                               |{{SC2-T}}
!colspan=4 align=left style=""border-right: 1px solid #777; border-top: 1px solid #777;""                               |{{SC2-Z}}
!colspan=4 align=left style=""border-right: 1px solid #777; border-top: 1px solid #777;""                               |{{SC2-P}}
");
            
            #line 11 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
 if (this.IncludeVs) { 
            
            #line default
            #line hidden
            this.Write(@"!colspan=4 align=left style=""border-right: 1px solid #777; border-top: 1px solid #777;""                               |vs. {{SC2-T}}
!colspan=4 align=left style=""border-right: 1px solid #777; border-top: 1px solid #777;""                               |vs. {{SC2-Z}}
!colspan=4 align=left style=""border-right: 1px solid #777; border-top: 1px solid #777;""                               |vs. {{SC2-P}}
");
            
            #line 15 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"|-

!style=""border-left: 1px solid #777;"" width=2px      |
!style=""border-right: 1px solid #777;"" width=175px   |Team
<!-- Terran -->                                      !Sets
                                                     !Won
                                                     !Lost
!style=""border-right: 1px solid #777;""               |Win %
<!-- Zerg -->                                        !Sets
                                                     !Won
                                                     !Lost
!style=""border-right: 1px solid #777;""               |Win %
<!-- Protoss -->                                     !Sets
                                                     !Won
                                                     !Lost
!style=""border-right: 1px solid #777;""               |Win %
");
            
            #line 32 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
 if (this.IncludeVs) { 
            
            #line default
            #line hidden
            this.Write(@"<!-- Terran -->                                      !Sets
                                                     !Won
                                                     !Lost
!style=""border-right: 1px solid #777;""               |Win %
<!-- Zerg -->                                        !Sets
                                                     !Won
                                                     !Lost
!style=""border-right: 1px solid #777;""               |Win %
<!-- Protoss -->                                     !Sets
                                                     !Won
                                                     !Lost
!style=""border-right: 1px solid #777;""               |Win %
");
            
            #line 45 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
 } 
            
            #line default
            #line hidden
            
            #line 46 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
 foreach (Bag bag in this.Rows) { 
            
            #line default
            #line hidden
            this.Write("|-\r\n|style=\"border-left: 1px solid #777;\"                | ");
            
            #line 48 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["index"]));
            
            #line default
            #line hidden
            this.Write("\r\n|align=left style=\"border-right: 1px solid #777;\"    | {{team/");
            
            #line 49 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["team"]));
            
            #line default
            #line hidden
            this.Write("}}\r\n<!-- Terran -->                                      | ");
            
            #line 50 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["Ttotal"]));
            
            #line default
            #line hidden
            this.Write("\r\n                                                     | ");
            
            #line 51 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["Twin"]));
            
            #line default
            #line hidden
            this.Write("\r\n                                                     | ");
            
            #line 52 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["Tloss"]));
            
            #line default
            #line hidden
            this.Write("\r\n|style=\"border-right: 1px solid #777;\"               | ");
            
            #line 53 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["Tpc"]));
            
            #line default
            #line hidden
            this.Write("\r\n<!-- Zerg -->                                        | ");
            
            #line 54 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["Ztotal"]));
            
            #line default
            #line hidden
            this.Write("\r\n                                                     | ");
            
            #line 55 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["Zwin"]));
            
            #line default
            #line hidden
            this.Write("\r\n                                                     | ");
            
            #line 56 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["Zloss"]));
            
            #line default
            #line hidden
            this.Write("\r\n|style=\"border-right: 1px solid #777;\"               | ");
            
            #line 57 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["Zpc"]));
            
            #line default
            #line hidden
            this.Write("\r\n<!-- Protoss -->                                     | ");
            
            #line 58 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["Ptotal"]));
            
            #line default
            #line hidden
            this.Write("\r\n                                                     | ");
            
            #line 59 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["Pwin"]));
            
            #line default
            #line hidden
            this.Write("\r\n                                                     | ");
            
            #line 60 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["Ploss"]));
            
            #line default
            #line hidden
            this.Write("\r\n|style=\"border-right: 1px solid #777;\"               | ");
            
            #line 61 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["Ppc"]));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 62 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
 if (this.IncludeVs) { 
            
            #line default
            #line hidden
            this.Write("<!-- Terran -->                                      | ");
            
            #line 63 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["vTtotal"]));
            
            #line default
            #line hidden
            this.Write("\r\n                                                     | ");
            
            #line 64 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["vTwin"]));
            
            #line default
            #line hidden
            this.Write("\r\n                                                     | ");
            
            #line 65 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["vTloss"]));
            
            #line default
            #line hidden
            this.Write("\r\n|style=\"border-right: 1px solid #777;\"               | ");
            
            #line 66 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["vTpc"]));
            
            #line default
            #line hidden
            this.Write("\r\n<!-- Zerg -->                                        | ");
            
            #line 67 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["vZtotal"]));
            
            #line default
            #line hidden
            this.Write("\r\n                                                     | ");
            
            #line 68 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["vZwin"]));
            
            #line default
            #line hidden
            this.Write("\r\n                                                     | ");
            
            #line 69 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["vZloss"]));
            
            #line default
            #line hidden
            this.Write("\r\n|style=\"border-right: 1px solid #777;\"               | ");
            
            #line 70 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["vZpc"]));
            
            #line default
            #line hidden
            this.Write("\r\n<!-- Protoss -->                                     | ");
            
            #line 71 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["vPtotal"]));
            
            #line default
            #line hidden
            this.Write("\r\n                                                     | ");
            
            #line 72 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["vPwin"]));
            
            #line default
            #line hidden
            this.Write("\r\n                                                     | ");
            
            #line 73 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["vPloss"]));
            
            #line default
            #line hidden
            this.Write("\r\n|style=\"border-right: 1px solid #777;\"               | ");
            
            #line 74 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bag["vPpc"]));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 75 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
 } 
            
            #line default
            #line hidden
            
            #line 76 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
 } 
            
            #line default
            #line hidden
            this.Write("|-\r\n!colspan=2 style=\"border-bottom: 1px solid #777; border-right: 1px solid #777" +
                    "; border-left: 1px solid #777;\" | Overall\r\n!style=\"border-bottom: 1px solid #777" +
                    "; \"                <!-- Terran --> | ");
            
            #line 79 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["Ttotal"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"\t\t\t\t\t\t\t\t| ");
            
            #line 80 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["Twin"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"\t\t\t\t\t\t\t\t| ");
            
            #line 81 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["Tloss"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; border-right: 1px solid #777;\"   | ");
            
            #line 82 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["Tpc"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"                  <!-- Zerg --> | ");
            
            #line 83 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["Ztotal"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"\t\t\t\t\t\t\t\t| ");
            
            #line 84 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["Zwin"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"\t\t\t\t\t\t\t\t| ");
            
            #line 85 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["Zloss"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; border-right: 1px solid #777;\"   | ");
            
            #line 86 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["Zpc"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"               <!-- Protoss --> | ");
            
            #line 87 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["Ptotal"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"\t\t\t\t\t\t\t\t| ");
            
            #line 88 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["Pwin"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"\t\t\t\t\t\t\t\t| ");
            
            #line 89 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["Ploss"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; border-right: 1px solid #777;\"   | ");
            
            #line 90 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["Ppc"]));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 91 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
 if (this.IncludeVs) { 
            
            #line default
            #line hidden
            this.Write("!style=\"border-bottom: 1px solid #777; \"                <!-- Terran --> | ");
            
            #line 92 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["vTtotal"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"\t\t\t\t\t\t\t\t| ");
            
            #line 93 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["vTwin"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"\t\t\t\t\t\t\t\t| ");
            
            #line 94 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["vTloss"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; border-right: 1px solid #777;\"   | ");
            
            #line 95 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["vTpc"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"                  <!-- Zerg --> | ");
            
            #line 96 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["vZtotal"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"\t\t\t\t\t\t\t\t| ");
            
            #line 97 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["vZwin"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"\t\t\t\t\t\t\t\t| ");
            
            #line 98 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["vZloss"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; border-right: 1px solid #777;\"   | ");
            
            #line 99 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["vZpc"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"               <!-- Protoss --> | ");
            
            #line 100 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["vPtotal"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"\t\t\t\t\t\t\t\t| ");
            
            #line 101 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["vPwin"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; \"\t\t\t\t\t\t\t\t| ");
            
            #line 102 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["vPloss"]));
            
            #line default
            #line hidden
            this.Write("\r\n!style=\"border-bottom: 1px solid #777; border-right: 1px solid #777;\"   | ");
            
            #line 103 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Params["vPpc"]));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 104 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"<!-- |-
!colspan=2 align=left style=""border-left: 1px solid #777; border-bottom: 1px solid #777; border-right: 1px solid #777;""  |
!colspan=4 align=left style=""border-bottom: 1px solid #777; border-right: 1px solid #777;""                               |
!colspan=4 align=left style=""border-bottom: 1px solid #777; border-right: 1px solid #777;""                               |
!colspan=4 align=left style=""border-bottom: 1px solid #777; border-right: 1px solid #777;""                               | -->
|}
");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 111 "E:\git\xpaperclip\lpcarnotools\zero\LpCarno\Templates\RacialStatistics.tt"

public bool IncludeVs { get; set; }
public Bag Params { get; set; }
public IEnumerable<Bag> Rows { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class RacialStatisticsBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
